# Generated by Django 5.1.4 on 2025-01-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_books_genre_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='book',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
