# Generated by Django 5.1.4 on 2025-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_member_remove_transaction_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_img',
            field=models.ImageField(default='books/default.jpg', upload_to='books'),
        ),
    ]
