# Generated by Django 5.1.4 on 2025-01-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_books_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_img',
        ),
    ]
