# Generated by Django 5.1.4 on 2025-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_books_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Paranormal', 'Paranormal'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Action Adventure', 'Action Adventure'), ('Fiction', 'Fiction')], default='', max_length=50),
        ),
    ]
